// 公开只读分享页：无需登录即可查看的品牌化报告页（传播闭环）。
import { publicFileList, publicPreviewFile, publicDownloadUrl } from "./infini.js";
import { locOf, type Vertical, type Lang } from "./verticals.js";
import type { Report, Chart } from "./jobs.js";

// 极简 markdown -> html（标题/加粗/列表/段落）
function mdToHtml(md: string): string {
  if (!md) return "";
  const esc = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  const lines = md.split(/\r?\n/);
  let html = "";
  let inList = false;
  for (let line of lines) {
    const raw = line.trim();
    if (!raw) {
      if (inList) { html += "</ul>"; inList = false; }
      continue;
    }
    let h = esc(raw);
    h = h.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
    if (/^#{1,6}\s/.test(raw)) {
      if (inList) { html += "</ul>"; inList = false; }
      const level = Math.min(raw.match(/^#+/)![0].length, 4) + 1;
      html += `<h${level}>${h.replace(/^#{1,6}\s/, "")}</h${level}>`;
    } else if (/^[-*]\s/.test(raw) || /^\d+[.)]\s/.test(raw)) {
      if (!inList) { html += "<ul>"; inList = true; }
      html += `<li>${h.replace(/^[-*]\s/, "").replace(/^\d+[.)]\s/, "")}</li>`;
    } else {
      if (inList) { html += "</ul>"; inList = false; }
      html += `<p>${h}</p>`;
    }
  }
  if (inList) html += "</ul>";
  return html;
}

// 从公开接口加载报告内容（图表 SVG + 报告正文 + PDF 下载）
async function loadFromPublic(taskId: string): Promise<{ charts: Chart[]; summary: string; pdfUrl: string }> {
  try {
    const files = await publicFileList(taskId);
    const charts: Chart[] = [];
    for (const f of files.filter((x) => x.ext === "svg" && !x.isDir).slice(0, 8)) {
      try {
        const { content } = await publicPreviewFile(taskId, f.name);
        if (content && content.includes("<svg")) {
          charts.push({ name: f.name.replace(/\.svg$/i, ""), svg: content });
        }
      } catch {
        /* skip */
      }
    }
    let summary = "";
    const md = files.find((x) => x.ext === "md" && !x.isDir && !/stats/i.test(x.name) && !x.name.includes("/"));
    if (md) {
      try {
        summary = (await publicPreviewFile(taskId, md.name)).content || "";
      } catch {
        /* skip */
      }
    }
    const pdf = files.find((x) => x.ext === "pdf" && !x.isDir);
    return { charts, summary, pdfUrl: pdf ? publicDownloadUrl(taskId, pdf.name) : "" };
  } catch {
    return { charts: [], summary: "", pdfUrl: "" };
  }
}

export async function renderSharePage(
  taskId: string,
  V: Vertical,
  lang: Lang,
  cached?: Report
): Promise<string> {
  const L = locOf(V, lang);
  const en = lang === "en";
  const T = {
    reportTitle: en ? `${L.name} Report` : `${L.name}报告`,
    badge: en ? "Generated by the InfiniSynapse analytics engine" : "由 InfiniSynapse 泛数据分析引擎生成",
    viz: en ? "Visualizations" : "数据可视化",
    generating: en ? "The report is being generated. Please refresh shortly." : "报告正在生成中，请稍后刷新查看完整内容。",
    pdf: en ? "⬇ Download PDF" : "⬇ 下载 PDF 报告",
    cta: en ? "Upload your data to generate your own report" : "上传数据，生成你的专属分析报告",
    footer: en ? "Analytics powered by" : "分析能力由",
    footerTail: en ? "· natural-language data analysis" : "× CSDN 提供 · 自然语言驱动的泛数据分析",
    signupCard: en
      ? "This report was generated by the InfiniSynapse engine. Sign up to analyze your own data — new users get free credits."
      : "这份报告由 InfiniSynapse 引擎生成。注册即可用它分析你自己的数据，新用户可领免费体验额度。",
    signupBtn: en ? "Sign up free →" : "免费注册 →",
    signupFoot: en ? "Sign up free" : "免费注册",
  };
  // InfiniSynapse 注册/登录入口（拉新引导，文案不写死额度数额）
  const APP_URL = "https://app.infinisynapse.cn";
  let charts: Chart[] = cached?.charts || [];
  let summary = cached?.summary || "";
  let pdfUrl = "";
  if (!charts.length || !summary) {
    const pub = await loadFromPublic(taskId);
    if (!charts.length) charts = pub.charts;
    if (!summary) summary = pub.summary;
    pdfUrl = pub.pdfUrl;
  }
  summary = summary.replace(/!\[[^\]]*\]\([^)]*\)/g, "").replace(/\n{3,}/g, "\n\n");

  const chartsHtml = charts
    .map((c) => `<div class="chart"><h3>${c.name}</h3><div class="svgbox">${c.svg}</div></div>`)
    .join("");
  const summaryHtml = summary
    ? `<div class="summary">${mdToHtml(summary)}</div>`
    : `<p class="muted">${T.generating}</p>`;

  return `<!DOCTYPE html>
<html lang="${en ? "en" : "zh-CN"}"><head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>${T.reportTitle} · InfiniSynapse</title>
<meta property="og:title" content="${T.reportTitle}"/>
<meta property="og:description" content="${L.tagline}"/>
<style>
  @font-face { font-family:"Noto Sans SC UI"; font-weight:700; font-display:swap; src:url("/gen/fonts/NotoSC-700.woff2") format("woff2"); }
  :root{--brand:${V.brandColor};--accent:${V.accentColor}}
  *{box-sizing:border-box}
  body{margin:0;font-family:-apple-system,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif;background:#f5f7fa;color:#101828;line-height:1.65;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}
  .hero h1,.card h2,.summary h1,.summary h2{font-family:"Noto Sans SC UI",-apple-system,"PingFang SC","Microsoft YaHei",sans-serif}
  .wrap{max-width:780px;margin:0 auto;padding:24px 16px 60px}
  .hero{background:linear-gradient(135deg,var(--brand),var(--accent));color:#fff;border-radius:18px;padding:30px 26px;box-shadow:0 14px 34px rgba(16,24,40,.14)}
  .hero .badge{display:inline-block;background:rgba(255,255,255,.18);border:1px solid rgba(255,255,255,.25);padding:4px 13px;border-radius:999px;font-size:12.5px;margin-bottom:12px}
  .hero h1{margin:0 0 6px;font-size:25px}
  .hero p{margin:0;opacity:.94}
  .card{background:#fff;border:1px solid #e4e7ec;border-radius:14px;padding:22px 24px;margin-top:18px}
  .card h2{color:var(--brand);margin-top:0;font-size:18px}
  .summary h1{font-size:22px}
  .summary h2,.summary h3,.summary h4{color:var(--brand);margin:18px 0 6px}
  .summary ul,.summary ol{padding-left:22px;margin:8px 0}
  .summary li{margin:4px 0}
  .summary table{width:100%;border-collapse:collapse;margin:12px 0;font-size:14px}
  .summary th,.summary td{border:1px solid #e4e7ec;padding:8px 12px;text-align:left}
  .summary th{background:#f9fafb}
  .summary blockquote{border-left:3px solid var(--brand);background:#f9fafb;margin:12px 0;padding:8px 14px;border-radius:6px;color:#475467}
  .chart{margin-top:16px}
  .chart h3{font-size:15px;color:#344054;margin:0 0 8px}
  .svgbox{overflow-x:auto;text-align:center;border:1px solid #e4e7ec;border-radius:10px;padding:10px;background:#fff}
  .svgbox svg{max-width:100%;height:auto}
  .muted{color:#667085}
  .cta{margin-top:26px;text-align:center;display:flex;gap:12px;justify-content:center;flex-wrap:wrap}
  .cta a{display:inline-block;background:var(--brand);color:#fff;text-decoration:none;padding:12px 26px;border-radius:10px;font-weight:600;box-shadow:0 8px 20px rgba(47,111,237,.28)}
  .cta a.pdf{background:#fff;color:var(--brand);border:1px solid var(--brand);box-shadow:none}
  .footer{margin-top:22px;text-align:center;color:#98a2b3;font-size:13px}
  .footer a{color:var(--brand);text-decoration:none}
  .signup{margin-top:22px;text-align:center;background:#fff;border:1px solid #e4e7ec;border-radius:14px;padding:24px 20px}
  .signup p{margin:0 auto 14px;max-width:520px;color:#475467;font-size:14px;line-height:1.7}
  .signup a{display:inline-block;border:1px solid var(--brand);color:var(--brand);text-decoration:none;padding:9px 22px;border-radius:999px;font-weight:600;font-size:14px;transition:background .2s,color .2s}
  .signup a:hover{background:var(--brand);color:#fff}
</style></head>
<body><div class="wrap">
  <div class="hero">
    <span class="badge">${T.badge}</span>
    <h1>${T.reportTitle}</h1>
    <p>${L.tagline}</p>
  </div>
  <div class="card">${summaryHtml}</div>
  ${chartsHtml ? `<div class="card"><h2>${T.viz}</h2>${chartsHtml}</div>` : ""}
  <div class="cta">
    ${pdfUrl ? `<a class="pdf" href="${pdfUrl}" target="_blank">${T.pdf}</a>` : ""}
    <a href="/">${T.cta}</a>
  </div>
  <div class="signup">
    <p>${T.signupCard}</p>
    <a href="${APP_URL}" target="_blank" rel="noopener noreferrer">${T.signupBtn}</a>
  </div>
  <div class="footer">
    ${T.footer} <a href="https://infinisynapse.cn" target="_blank">InfiniSynapse</a> ${T.footerTail} · <a href="${APP_URL}" target="_blank" rel="noopener noreferrer">${T.signupFoot}</a>
  </div>
</div></body></html>`;
}
